version: 2


workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - lint:
        requires:
          - test
      - deploy:
          context: npm-publish
          requires:
            - test
            - lint
          filters:
            branches:
              only:
                - master

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run Tests
          command: yarn test
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      
      - persist_to_workspace:
          root: ~/repo
          paths: .
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/code
      - run:
          name: Lint source
          command: yarn ci:lint
      - store_test_results:
          path: ./reports
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish package
          command: yarn publish